Egoi2022/egoi-tienda-react

src/components/home/bannerdown.js, src/components/home/recientes.js, src/styles/recientes.css
changues in buttons right or left of cards in home
=> perf: :zap: changues in the home

src/components/cart/checkout.tsx, src/components/cart/detailCart.tsx, src/components/home/banner.js, src/components/home/recientes.js, src/services/categories.js, src/styles/recientes.css
cambios en el respponsive carousel, cambios en los tamanios de los banners
=> build: :bug: cambios menores

src/components/categories/productsCategories.tsx, src/styles/productCategories.css
=> fix: products cards grid

src/components/ticketSuport/modalTicketSupport/modalCancelarTicketSupport.js, src/components/ticketSuport/ticketSuport.tsx, src/services/ordenes.js
add endpoints for delete ticketsSupport
=> feat: :construction: delete ticket

src/components/tracking/trackSearch.tsx, src/styles/myOrders.css, src/styles/navbar.css
changues styles in seller modal
=> build: :bug: error seller modal

package-lock.json, package.json, src/App.js, src/components/brands/showBrands.tsx, src/components/cart/checkout.tsx, src/components/cart/detailCart.tsx, src/components/categories/productsCategories.tsx, src/components/contactacUsComponent.js, src/components/detailProduct/detailProduct.tsx, src/components/header.js, src/components/headerResponsive.js, src/components/ticketSuport/modalTicketSupport/modalAddNewTicket.js, src/constants/defaultValues.js, src/services/metodosDePago.js, src/styles/detailsCart.css, src/views/cartShopping.js, src/views/category.js, src/views/checkout/addressCart.js, src/views/detailsProduct.js, src/views/home.js, src/views/myOrders.js, src/views/politicaPrivacidad.js, src/views/sobreNosotros.js, src/views/terminosYCondiciones.js, src/views/user/addCart.js, src/views/user/metodosDePago/cashDeliveryOTP.js, src/views/user/metodosDePago/efecty.js, src/views/user/metodosDePago/modalNoPse.tsx
=> build: :zap: new features

src/components/detailProduct/detailProduct.tsx, src/styles/navbar.css
changues styles and validations
=> fix: :bug: buyNow params

src/components/FAQ.js, src/components/categories/productsCategories.tsx, src/components/home/banner.js
preguntas frecuentes acordion
search bar no funciona para mostrar el producto
banner 1 heigth estatico
centrar no hay productos para esta categoria
=> fix: :bug: fix bugs in faqs, searchBar and categoriesProducts

src/components/home/recientes.js, src/styles/recientes.css
Reverts Egoi2022/egoi-tienda-react#312
=> Revert "fix: changues"

src/components/home/recientes.js, src/styles/recientes.css
Reverts Egoi2022/egoi-tienda-react#313
=> Revert "Revert "fix: changues""

src/components/cart/checkout_V2.tsx, src/components/cart/checkout_V2_token.tsx, src/helpers/productsLocalStorage.js
changues and feat [fix bug carga de oproducto]:checkout
=> fix: :bug: changues

src/components/cart/checkout_V2_token.tsx
=> build: :bug: changues [checkout:address]

src/components/home/vendidos.js, src/styles/recientes.css, src/styles/vendidos.css
=> fix: :art: [home]

src/components/cart/checkout_V2_token.tsx, src/components/detailProduct/detailProduct.tsx
changues in loader buttons addToCart and buyNow, and checkout visibility method on payment
=> fix: :zap: [checkout][detailProduct]

src/components/detailProduct/detailProduct.tsx, src/styles/detailsProduct.css
=> fix: :art: changues [detailProducst]

src/components/cart/checkout_V2_token.tsx
visibility changues in methodPayment
=> fix: :fire: [checkout]

src/components/cart/checkout_V2.tsx, src/components/cart/checkout_V2_token.tsx
add tags purchase
changue styles
=> build: :bug: [checkout]

src/components/cart/checkout_V2.tsx, src/views/user/modalFillAll.js
=> feat: :art: [checkout]

src/views/user/metodosDePago/tarjetaCredito.js, src/views/user/metodosDePago/tarjetaDebito.js
=> fix: :art: [tarjetaCredito][tarjetaDebito]

src/components/cart/checkout_V2_token.tsx, src/components/cart/detailCartNoToken.tsx, src/components/cart/detailCartOffCanvasNoToken.tsx, src/components/detailProduct/detailProduct.tsx
changue visisibility and add buttons for the increment and decrement on the cart
=> fix: :bug: [checkout][detailCart][detailProduct]

src/components/detailProduct/detailProduct.tsx, src/components/headerResponsive.js, src/components/home/productsInCart.js
changues styles and validation objects, also backdrop false
=> fix: :zap: [detailProduct][headerResponsive][productInCart]
